# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 OrchIntel Systems Ltd.
# https://orchintel.com | https://ioa.systems
#
# Part of IOA Core (Open Source Edition). See LICENSE at repo root.


# Feature Toggle Configuration
# Each feature can be independently enabled/disabled without breaking others
features:
  # Vector search backend selection
  vector_search: "faiss"  # Options: "faiss", "tfidf", "off"
  
  # GDPR compliance hooks
  gdpr_hooks: "on"  # Options: "on", "off"
  
  # HIPAA redaction capabilities
  hipaa_redaction: "on"  # Options: "on", "off"
  
  # Cold storage encryption
  cold_storage_encryption: "on"  # Options: "on", "off"
  
  # Policy enforcement gate
  policy_gate: "on"  # Options: "on", "off"
  
  # Benchmarking capabilities
  benchmarks: "on"  # Options: "on", "off"

# Environment variable overrides (highest precedence)
# IOA_FEATURE_VECTOR_SEARCH=off
# IOA_FEATURE_GDPR_HOOKS=off
# IOA_FEATURE_HIPAA_REDACTION=off
# IOA_FEATURE_COLD_STORAGE_ENCRYPTION=off
# IOA_FEATURE_POLICY_GATE=off
# IOA_FEATURE_BENCHMARKS=off
