# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 OrchIntel Systems Ltd.
# https://orchintel.com | https://ioa.systems
#
# Part of IOA Core (Open Source Edition). See LICENSE at repo root.

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'ioa-alerts@company.com'
  smtp_auth_username: 'ioa-alerts@company.com'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'ioa-alerts'
  routes:
  - match:
      severity: critical
    receiver: 'ioa-critical'
  - match:
      severity: warning
    receiver: 'ioa-warning'

receivers:
- name: 'ioa-alerts'
  email_configs:
  - to: 'ioa-team@company.com'
    subject: '[IOA Alert] {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}

- name: 'ioa-critical'
  email_configs:
  - to: 'ioa-oncall@company.com'
    subject: '[CRITICAL IOA] {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL ALERT: {{ .Annotations.summary }}
      {{ .Annotations.description }}
      
      Affected Services: {{ .GroupLabels.service }}
      Time: {{ .StartsAt }}
      
      Please investigate immediately.
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#ioa-critical'
    title: 'IOA Critical Alert'
    text: '{{ .Annotations.summary }} - {{ .Annotations.description }}'

- name: 'ioa-warning'
  email_configs:
  - to: 'ioa-team@company.com'
    subject: '[WARNING IOA] {{ .GroupLabels.alertname }}'
    body: |
      Warning: {{ .Annotations.summary }}
      {{ .Annotations.description }}
      
      Time: {{ .StartsAt }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#ioa-warnings'
    title: 'IOA Warning'
    text: '{{ .Annotations.summary }} - {{ .Annotations.description }}'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
