# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 OrchIntel Systems Ltd.
# https://orchintel.com | https://ioa.systems
#
# Part of IOA Core (Open Source Edition). See LICENSE at repo root.

# governance.config.yaml
# Governance configuration for IOA Core.
# Controls modes, thresholds, and features across agents/memory/refinery.

# PATCH: Cursor-2025-08-21 DISPATCH-GPT-20250821-007 <agent-to-model terminology refactor>

roundtable_mode_enabled: true
consensus_threshold: 0.7  # For collation (e.g., avg_vote * agreement > threshold)
pattern_court_enabled: true  # Enables PatternGovernance validation/deprecation
weaver_batch_size: 10  # Unclassified threshold for PatternWeaver
preservation_auto_detect: true  # Enables format-based preservation
kpi_monitor_enabled: true  # Tracks match/unclassified/compaction rates
vad_emotion_enabled: true  # SentienceMapper for feeling vectors
relevance_threshold: 0.7  # For compaction discard in digest_entry
debug_flags:
  - trace-routing  # Show model selections/token costs
  - log-memory-diff  # Track memory changes

# ONBOARD-001 tenant isolation settings
ONBOARD-001:
  tenant_isolation_enabled: true


