# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 OrchIntel Systems Ltd.
# https://orchintel.com | https://ioa.systems
#
# Part of IOA Core (Open Source Edition). See LICENSE at repo root.

# IOA Staging Configuration
# Production-ready settings for staged rollout

# Authentication
auth:
  require_auth: true
  auth_token: "${IOA_AUTH_TOKEN}"  # Must be set in environment
  
# Signing Backend
signing:
  backend: "kms"  # Use KMS in staging
  kms_key_id: "${IOA_KMS_KEY_ID}"
  verify_skip: false  # Always verify in staging
  
# Audit Chain Security
audit:
  encrypt_manifest: true
  enc_key_b64: "${IOA_AUDIT_ENC_KEY_B64}"
  batch_size: 100
  backpressure: true
  backpressure_threshold: 1000
  
# Circuit Breakers
circuit_breakers:
  s3:
    failure_threshold: 5
    recovery_timeout: 30
    connection_pool_size: 10
    max_retries: 3
    retry_delay: 1
    health_check_interval: 60
    
  kms:
    failure_threshold: 3
    recovery_timeout: 60
    timeout: 10
    
# Cartridge Sandbox
cartridge:
  sandbox: true  # Enable sandboxing in staging
  
# Operator Identity
operator:
  id: "${IOA_OPERATOR_ID}"
  role: "${IOA_OPERATOR_ROLE}"
  
# Trusted Timestamping
tsa:
  url: "${IOA_TSA_URL}"
  nonce: "${IOA_TSA_NONCE}"
  out_dir: "/tmp/ioa-tsa"
  verify: true
  ca_file: "${IOA_TSA_CA_FILE}"
