# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 OrchIntel Systems Ltd.

"""Bootstrap a new IOA project with minimal scaffolding."""

from pathlib import Path


def main(name: str = "my-ai-system"):
    """Create a new IOA project with basic structure.
    
    Args:
        name: Project name (default: my-ai-system)
    """
    root = Path.cwd() / name
    root.mkdir(exist_ok=True)
    
    # Create ioa.yaml configuration
    (root / "ioa.yaml").write_text(
        f"version: 1\nproject: {name}\n"
    )
    
    # Create README
    (root / "README.md").write_text(
        f"# {name}\n\nGenerated by IOA bootstrap.\n\n"
        "## Getting Started\n\n"
        "Configure your LLM providers in `.env` and start building!\n"
    )
    
    print(f"✅ Project scaffolded at ./{name}")
    print(f"   - {name}/ioa.yaml (configuration)")
    print(f"   - {name}/README.md (project docs)")


if __name__ == "__main__":
    import sys
    name = sys.argv[1] if len(sys.argv) > 1 else "my-ai-system"
    main(name)

